### PR TITLE
Increase verification grace period and restart ntp immediately

### PR DESCRIPTION
**Pull request by EdHurtig**
See #3 and #5

See Also: https://github.com/gmiranda23/ntp/blob/master/recipes/default.rb#L80-L90

Attempt 2 to fix initial convergence issues.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Seems like this might do the trick, code looks good. :+1: wanna cut a new release & :shipit:?

**Comment by EdHurtig** [comment]
Will :shipit: tonight hopefully if things go well

**Comment by jeffbyrnes** [comment]
@EdHurtig how’d this go?

**Comment by EdHurtig** [comment]
@jeffbyrnes Had no time last night... deploying now

**Comment by EdHurtig** [comment]
Pushed to stage this morning... Provisioned 3 boxes... no errors! Woo!

Confirmed that service is restarting immediately as well

**Comment by jeffbyrnes** [comment]
Hot damn! Well done, sir.

**Pull request merged**
