### PR TITLE
Verify ntp pool connectivity

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by EdHurtig** [comment]
See 5d97433 on server-chef, there is some other monitoring related stuff there

**Comment by eherot** [comment]
@EdHurtig these do two different things. This is really designed to fail if something is broken during convergence.

**Comment by EdHurtig** [comment]
Yeah I am aware of that... It just sparked that issue I alluded to and I wanted to highlight it

**Comment by eherot** [comment]
@EdHurtig makes sense. :+1:

**Comment by jeffbyrnes** [comment]
:+1: from me

**Pull request merged**
